name: 'Test Migration MS'
description: 'Queima Labs DevOps Stack - Test Migration - Docker-Compose File'
inputs:
  access_token:  # ID Service
    description: Personal Access Token - Scope read:pkg
    required: true
  service_port:  # ID Service
    description: Port where service is Exposed
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:      
    - name: Configure NPM
      shell: bash
      env:
        PAT: ${{ inputs.access_token }}
        WORKSPACE: ${{ github.workspace }}
      run: |
        echo $WORKSPACE
        cd $WORKSPACE
        
        cat <<EOF > .npmrc
        @queimadiaria:registry=https://npm.pkg.github.com/
        //npm.pkg.github.com/:_authToken=${PAT}
        EOF

    - name: Run Test Migration container
      env:
        ENVIRONMENT: ""
        FILE: config/environment.config.sh
        WORKSPACE: ${{ github.workspace }}
      shell: bash
      run: |
        echo $WORKSPACE
        cd ${WORKSPACE}

        if test -f "${FILE}"; then
          bash ${FILE} 
          docker-compose -f $DOCKER_COMPOSE  up -d --build 
        else
          echo "The File ${FILE} doesn't exitis"
        fi

    - name: Check API healthckeck
      shell: bash
      env:
        PORT: ${{ inputs.service_port }}
      run: |
        echo ${{inputs.service_port}}
        echo  "http://localhost:${PORT}/health"
        sleep 15 \
        && curl -sf \
          http://localhost:${PORT}/health \
        || (docker-compose logs api && exit 1)